### ISSUE TITLE
Upstream plans

### ISSUE THREAD

**Issue by jamestiotio** [Cerebras/libtins#8]
Hi there!

I was looking into some particular use cases for the `libtins` library when I happened to come across this fork. It seems that there have been some significant contributions made by the Cerebras team. I was wondering whether there are any pending plans to upstream the changes made in this fork.

For example, the changes in #3 were related to [this upstream discussion](https://github.com/mfontanini/libtins/issues/269). @ebertland also mentioned upstreaming some enhancements [here](https://github.com/Cerebras/libtins/pull/6#issuecomment-1387659353). It would be great to have these changes upstream to benefit the rest of the community as well. 😄

**Comment by ebertland** [comment]
Some of these changes are quite extensive, particularly the PR for malformed_packet exceptions. I appreciate your interest, though, and I'll try to get (at least some of) them upstreamed.

**Comment by jamestiotio** [comment]
Sure, that sounds good!

Do keep in mind that it was never my intention to rush the upstreaming process. I understand that some of the changes are touching a lot of files. Even so, I believe that the team has performed extensive testing of the changes internally so far to ensure their level of quality. Careful review with the upstream maintainer would hopefully also allow us to find and fix any remaining rough edges.

I will close this issue for now. I will let the team upstream the changes whenever you have the time and find it convenient to do so.
